// Admin
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const CHECKED_ADMIN_ACCESS = 'CHECKED_ADMIN_ACCESS';

// User Search
export const CLEARED_SEARCH_RESULTS = 'CLEARED_SEARCH_RESULTS';
export const RECEIVED_USERS = 'RECEIVED_USERS';
export const SEARCHED_USERS = 'SEARCHED_USERS';

// Repos by User
export const RECEIVED_USER_REPOS = 'RECEIVED_USER_REPOS';
export const REQUESTED_USER_REPOS = 'REQUESTED_USER_REPOS';

// Login
export const LOGIN = 'LOGIN';
export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const CHANGE_PASSWORD_PENDING = 'CHANGE_PASSWORD_PENDING';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const CHANGE_EMAIL_PENDING = 'CHANGE_EMAIL_PENDING';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_EMAIL_ERROR = 'CHANGE_EMAIL_ERROR';
