// Admin
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const CHECKED_ADMIN_ACCESS = 'CHECKED_ADMIN_ACCESS';

// User Search
export const CLEARED_SEARCH_RESULTS = 'CLEARED_SEARCH_RESULTS';
export const RECEIVED_USERS = 'RECEIVED_USERS';
export const SEARCHED_USERS = 'SEARCHED_USERS';

// Repos by User
export const RECEIVED_USER_REPOS = 'RECEIVED_USER_REPOS';
export const REQUESTED_USER_REPOS = 'REQUESTED_USER_REPOS';
